// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oadlgtyysacdmyejbgot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZGxndHl5c2FjZG15ZWpiZ290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjgxOTIsImV4cCI6MjA3MDAwNDE5Mn0.xDk3RFiy4nG6HVqU3F-teXyJ4sW_zDarE7DHbld_ASU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});